/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
*
* Copyright 2013 - 2023, nymea GmbH
* Contact: contact@nymea.io
*
* This fileDescriptor is part of nymea.
* This project including source code and documentation is protected by
* copyright law, and remains the property of nymea GmbH. All rights, including
* reproduction, publication, editing and translation, are reserved. The use of
* this project is subject to the terms of a license agreement to be concluded
* with nymea GmbH in accordance with the terms of use of nymea GmbH, available
* under https://nymea.io/license
*
* GNU Lesser General Public License Usage
* Alternatively, this project may be redistributed and/or modified under the
* terms of the GNU Lesser General Public License as published by the Free
* Software Foundation; version 3. This project is distributed in the hope that
* it will be useful, but WITHOUT ANY WARRANTY; without even the implied
* warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
* Lesser General Public License for more details.
*
* You should have received a copy of the GNU Lesser General Public License
* along with this project. If not, see <https://www.gnu.org/licenses/>.
*
* For any further details and any questions please contact us under
* contact@nymea.io or see our FAQ/Licensing Information on
* https://nymea.io/license/faq
*
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
*
* WARNING
*
* This file has been autogenerated. Any changes in this file may be overwritten.
* If you want to change something, update the register json or the tool.
*
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

#include "a-eberle-pqi-da-smartmodbusrtuconnection.h"
#include <loggingcategories.h>
#include <math.h>
#include <QTimer>

NYMEA_LOGGING_CATEGORY(dca-eberle-pqi-da-smartModbusRtuConnection, "a-eberle-pqi-da-smartModbusRtuConnection")

a-eberle-pqi-da-smartModbusRtuConnection::a-eberle-pqi-da-smartModbusRtuConnection(ModbusRtuMaster *modbusRtuMaster, quint16 slaveId, QObject *parent) :
    QObject(parent),
    m_modbusRtuMaster(modbusRtuMaster),
    m_slaveId(slaveId)
{
    connect(m_modbusRtuMaster, &ModbusRtuMaster::connectedChanged, this, [=](bool connected){
        if (connected) {
            qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Modbus RTU resource" << m_modbusRtuMaster->serialPort() << "connected again. Start testing if the connection is reachable...";
            m_pendingInitReplies.clear();
            m_pendingUpdateReplies.clear();
            m_communicationWorking = false;
            m_communicationFailedCounter = 0;
            m_checkReachableRetriesCount = 0;
            testReachability();
        } else {
            qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Modbus RTU resource" << m_modbusRtuMaster->serialPort() << "disconnected. The connection is not reachable any more.";
            m_communicationWorking = false;
            m_communicationFailedCounter = 0;
            m_checkReachableRetriesCount = 0;
        }

        evaluateReachableState();
    });
}

ModbusRtuMaster *a-eberle-pqi-da-smartModbusRtuConnection::modbusRtuMaster() const
{
    return m_modbusRtuMaster;
}
quint16 a-eberle-pqi-da-smartModbusRtuConnection::slaveId() const
{
    return m_slaveId;
}

bool a-eberle-pqi-da-smartModbusRtuConnection::reachable() const
{
    return m_reachable;
}

uint a-eberle-pqi-da-smartModbusRtuConnection::checkReachableRetries() const
{
    return m_checkReachableRetries;
}

void a-eberle-pqi-da-smartModbusRtuConnection::setCheckReachableRetries(uint checkReachableRetries)
{
    if (m_checkReachableRetries == checkReachableRetries)
        return;

    m_checkReachableRetries = checkReachableRetries;
    emit checkReachableRetriesChanged(m_checkReachableRetries);
}

ModbusDataUtils::ByteOrder a-eberle-pqi-da-smartModbusRtuConnection::endianness() const
{
    return m_endianness;
}

void a-eberle-pqi-da-smartModbusRtuConnection::setEndianness(ModbusDataUtils::ByteOrder endianness)
{
    if (m_endianness == endianness)
        return;

    m_endianness = endianness;
    emit endiannessChanged(m_endianness);
}

float a-eberle-pqi-da-smartModbusRtuConnection::totalCurrentPower() const
{
    return m_totalCurrentPower;
}

float a-eberle-pqi-da-smartModbusRtuConnection::powerPhaseA() const
{
    return m_powerPhaseA;
}

float a-eberle-pqi-da-smartModbusRtuConnection::powerPhaseB() const
{
    return m_powerPhaseB;
}

float a-eberle-pqi-da-smartModbusRtuConnection::powerPhaseC() const
{
    return m_powerPhaseC;
}

float a-eberle-pqi-da-smartModbusRtuConnection::totalEnergyConsumed() const
{
    return m_totalEnergyConsumed;
}

float a-eberle-pqi-da-smartModbusRtuConnection::totalEnergyProduced() const
{
    return m_totalEnergyProduced;
}

float a-eberle-pqi-da-smartModbusRtuConnection::frequency() const
{
    return m_frequency;
}

float a-eberle-pqi-da-smartModbusRtuConnection::voltagePhaseA() const
{
    return m_voltagePhaseA;
}

float a-eberle-pqi-da-smartModbusRtuConnection::voltagePhaseB() const
{
    return m_voltagePhaseB;
}

float a-eberle-pqi-da-smartModbusRtuConnection::voltagePhaseC() const
{
    return m_voltagePhaseC;
}

float a-eberle-pqi-da-smartModbusRtuConnection::currentPhaseA() const
{
    return m_currentPhaseA;
}

float a-eberle-pqi-da-smartModbusRtuConnection::currentPhaseB() const
{
    return m_currentPhaseB;
}

float a-eberle-pqi-da-smartModbusRtuConnection::currentPhaseC() const
{
    return m_currentPhaseC;
}

bool a-eberle-pqi-da-smartModbusRtuConnection::initialize()
{
    if (!m_reachable) {
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Tried to initialize but the device is not to be reachable.";
        return false;
    }
    // No init registers defined. Nothing to be done and we are finished.
    emit initializationFinished(true);
    return true;
}

bool a-eberle-pqi-da-smartModbusRtuConnection::update()
{
    if (!m_modbusRtuMaster->connected()) {
        qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Tried to update the registers but the hardware resource seems not to be connected.";
        return false;
    }

    if (!m_pendingUpdateReplies.isEmpty()) {
        qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Tried to update the registers but there are still some update replies pending. Waiting for them to be finished...";
        return true;
    }

    // Hardware resource available but communication not working. 
    // Try to read the check reachability register to re-evaluatoe the communication... 
    if (m_modbusRtuMaster->connected() && !m_communicationWorking) {
        testReachability();
        return false;
    }

    ModbusRtuReply *reply = nullptr;

    // Read Total system power
    qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "--> Read \"Total system power\" register:" << 1964 << "size:" << 2;
    reply = readTotalCurrentPower();
    if (!reply) {
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Error occurred while reading \"Total system power\" registers";
        return false;
    }

    if (reply->isFinished()) {
        return false; // Broadcast reply returns immediatly
    }

    m_pendingUpdateReplies.append(reply);
    connect(reply, &ModbusRtuReply::finished, this, [this, reply](){
        handleModbusError(reply->error());
        m_pendingUpdateReplies.removeAll(reply);

        if (reply->error() != ModbusRtuReply::NoError) {
            verifyUpdateFinished();
            return;
        }

        QVector<quint16> values = reply->result();
        qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "<-- Response from \"Total system power\" register" << 1964 << "size:" << 2 << values;
        processTotalCurrentPowerRegisterValues(values);
        verifyUpdateFinished();
    });

    connect(reply, &ModbusRtuReply::errorOccurred, this, [reply] (ModbusRtuReply::Error error){
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "ModbusRtu reply error occurred while updating \"Total system power\" registers" << error << reply->errorString();
    });

    // Read Power phase L1
    qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "--> Read \"Power phase L1\" register:" << 1946 << "size:" << 2;
    reply = readPowerPhaseA();
    if (!reply) {
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Error occurred while reading \"Power phase L1\" registers";
        return false;
    }

    if (reply->isFinished()) {
        return false; // Broadcast reply returns immediatly
    }

    m_pendingUpdateReplies.append(reply);
    connect(reply, &ModbusRtuReply::finished, this, [this, reply](){
        handleModbusError(reply->error());
        m_pendingUpdateReplies.removeAll(reply);

        if (reply->error() != ModbusRtuReply::NoError) {
            verifyUpdateFinished();
            return;
        }

        QVector<quint16> values = reply->result();
        qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "<-- Response from \"Power phase L1\" register" << 1946 << "size:" << 2 << values;
        processPowerPhaseARegisterValues(values);
        verifyUpdateFinished();
    });

    connect(reply, &ModbusRtuReply::errorOccurred, this, [reply] (ModbusRtuReply::Error error){
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "ModbusRtu reply error occurred while updating \"Power phase L1\" registers" << error << reply->errorString();
    });

    // Read Power phase L2
    qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "--> Read \"Power phase L2\" register:" << 1952 << "size:" << 2;
    reply = readPowerPhaseB();
    if (!reply) {
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Error occurred while reading \"Power phase L2\" registers";
        return false;
    }

    if (reply->isFinished()) {
        return false; // Broadcast reply returns immediatly
    }

    m_pendingUpdateReplies.append(reply);
    connect(reply, &ModbusRtuReply::finished, this, [this, reply](){
        handleModbusError(reply->error());
        m_pendingUpdateReplies.removeAll(reply);

        if (reply->error() != ModbusRtuReply::NoError) {
            verifyUpdateFinished();
            return;
        }

        QVector<quint16> values = reply->result();
        qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "<-- Response from \"Power phase L2\" register" << 1952 << "size:" << 2 << values;
        processPowerPhaseBRegisterValues(values);
        verifyUpdateFinished();
    });

    connect(reply, &ModbusRtuReply::errorOccurred, this, [reply] (ModbusRtuReply::Error error){
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "ModbusRtu reply error occurred while updating \"Power phase L2\" registers" << error << reply->errorString();
    });

    // Read Power phase L3
    qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "--> Read \"Power phase L3\" register:" << 1958 << "size:" << 2;
    reply = readPowerPhaseC();
    if (!reply) {
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Error occurred while reading \"Power phase L3\" registers";
        return false;
    }

    if (reply->isFinished()) {
        return false; // Broadcast reply returns immediatly
    }

    m_pendingUpdateReplies.append(reply);
    connect(reply, &ModbusRtuReply::finished, this, [this, reply](){
        handleModbusError(reply->error());
        m_pendingUpdateReplies.removeAll(reply);

        if (reply->error() != ModbusRtuReply::NoError) {
            verifyUpdateFinished();
            return;
        }

        QVector<quint16> values = reply->result();
        qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "<-- Response from \"Power phase L3\" register" << 1958 << "size:" << 2 << values;
        processPowerPhaseCRegisterValues(values);
        verifyUpdateFinished();
    });

    connect(reply, &ModbusRtuReply::errorOccurred, this, [reply] (ModbusRtuReply::Error error){
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "ModbusRtu reply error occurred while updating \"Power phase L3\" registers" << error << reply->errorString();
    });

    // Read Total energy consumed
    qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "--> Read \"Total energy consumed\" register:" << 2184 << "size:" << 2;
    reply = readTotalEnergyConsumed();
    if (!reply) {
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Error occurred while reading \"Total energy consumed\" registers";
        return false;
    }

    if (reply->isFinished()) {
        return false; // Broadcast reply returns immediatly
    }

    m_pendingUpdateReplies.append(reply);
    connect(reply, &ModbusRtuReply::finished, this, [this, reply](){
        handleModbusError(reply->error());
        m_pendingUpdateReplies.removeAll(reply);

        if (reply->error() != ModbusRtuReply::NoError) {
            verifyUpdateFinished();
            return;
        }

        QVector<quint16> values = reply->result();
        qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "<-- Response from \"Total energy consumed\" register" << 2184 << "size:" << 2 << values;
        processTotalEnergyConsumedRegisterValues(values);
        verifyUpdateFinished();
    });

    connect(reply, &ModbusRtuReply::errorOccurred, this, [reply] (ModbusRtuReply::Error error){
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "ModbusRtu reply error occurred while updating \"Total energy consumed\" registers" << error << reply->errorString();
    });

    // Read Total energy produced
    qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "--> Read \"Total energy produced\" register:" << 2176 << "size:" << 2;
    reply = readTotalEnergyProduced();
    if (!reply) {
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Error occurred while reading \"Total energy produced\" registers";
        return false;
    }

    if (reply->isFinished()) {
        return false; // Broadcast reply returns immediatly
    }

    m_pendingUpdateReplies.append(reply);
    connect(reply, &ModbusRtuReply::finished, this, [this, reply](){
        handleModbusError(reply->error());
        m_pendingUpdateReplies.removeAll(reply);

        if (reply->error() != ModbusRtuReply::NoError) {
            verifyUpdateFinished();
            return;
        }

        QVector<quint16> values = reply->result();
        qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "<-- Response from \"Total energy produced\" register" << 2176 << "size:" << 2 << values;
        processTotalEnergyProducedRegisterValues(values);
        verifyUpdateFinished();
    });

    connect(reply, &ModbusRtuReply::errorOccurred, this, [reply] (ModbusRtuReply::Error error){
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "ModbusRtu reply error occurred while updating \"Total energy produced\" registers" << error << reply->errorString();
    });

    // Read phaseVoltageAndFrequency
    qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "--> Read block \"phaseVoltageAndFrequency\" registers from:" << 1008 << "size:" << 8;
    reply = readBlockPhaseVoltageAndFrequency();
    if (!reply) {
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Error occurred while reading block \"phaseVoltageAndFrequency\" registers";
        return false;
    }

    if (reply->isFinished()) {
        return false; // Broadcast reply returns immediatly
    }

    m_pendingUpdateReplies.append(reply);
    connect(reply, &ModbusRtuReply::finished, this, [this, reply](){
        handleModbusError(reply->error());
        m_pendingUpdateReplies.removeAll(reply);

        if (reply->error() != ModbusRtuReply::NoError) {
            verifyUpdateFinished();
            return;
        }

        QVector<quint16> blockValues = reply->result();
        qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "<-- Response from reading block \"phaseVoltageAndFrequency\" register" << 1008 << "size:" << 8 << blockValues;
        processFrequencyRegisterValues(blockValues.mid(0, 2));
        processVoltagePhaseARegisterValues(blockValues.mid(2, 2));
        processVoltagePhaseBRegisterValues(blockValues.mid(4, 2));
        processVoltagePhaseCRegisterValues(blockValues.mid(6, 2));
        verifyUpdateFinished();
    });

    connect(reply, &ModbusRtuReply::errorOccurred, this, [reply] (ModbusRtuReply::Error error){
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "ModbusRtu reply error occurred while updating block \"phaseVoltageAndFrequency\" registers" << error << reply->errorString();
    });


    // Read phaseCurrent
    qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "--> Read block \"phaseCurrent\" registers from:" << 1586 << "size:" << 6;
    reply = readBlockPhaseCurrent();
    if (!reply) {
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Error occurred while reading block \"phaseCurrent\" registers";
        return false;
    }

    if (reply->isFinished()) {
        return false; // Broadcast reply returns immediatly
    }

    m_pendingUpdateReplies.append(reply);
    connect(reply, &ModbusRtuReply::finished, this, [this, reply](){
        handleModbusError(reply->error());
        m_pendingUpdateReplies.removeAll(reply);

        if (reply->error() != ModbusRtuReply::NoError) {
            verifyUpdateFinished();
            return;
        }

        QVector<quint16> blockValues = reply->result();
        qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "<-- Response from reading block \"phaseCurrent\" register" << 1586 << "size:" << 6 << blockValues;
        processCurrentPhaseARegisterValues(blockValues.mid(0, 2));
        processCurrentPhaseBRegisterValues(blockValues.mid(2, 2));
        processCurrentPhaseCRegisterValues(blockValues.mid(4, 2));
        verifyUpdateFinished();
    });

    connect(reply, &ModbusRtuReply::errorOccurred, this, [reply] (ModbusRtuReply::Error error){
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "ModbusRtu reply error occurred while updating block \"phaseCurrent\" registers" << error << reply->errorString();
    });


    // Read phasePower
    qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "--> Read block \"phasePower\" registers from:" << 0 << "size:" << 0;
    reply = readBlockPhasePower();
    if (!reply) {
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Error occurred while reading block \"phasePower\" registers";
        return false;
    }

    if (reply->isFinished()) {
        return false; // Broadcast reply returns immediatly
    }

    m_pendingUpdateReplies.append(reply);
    connect(reply, &ModbusRtuReply::finished, this, [this, reply](){
        handleModbusError(reply->error());
        m_pendingUpdateReplies.removeAll(reply);

        if (reply->error() != ModbusRtuReply::NoError) {
            verifyUpdateFinished();
            return;
        }

        QVector<quint16> blockValues = reply->result();
        qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "<-- Response from reading block \"phasePower\" register" << 0 << "size:" << 0 << blockValues;
        verifyUpdateFinished();
    });

    connect(reply, &ModbusRtuReply::errorOccurred, this, [reply] (ModbusRtuReply::Error error){
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "ModbusRtu reply error occurred while updating block \"phasePower\" registers" << error << reply->errorString();
    });


    // Read frequencyAndTotalEnergy
    qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "--> Read block \"frequencyAndTotalEnergy\" registers from:" << 0 << "size:" << 0;
    reply = readBlockFrequencyAndTotalEnergy();
    if (!reply) {
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Error occurred while reading block \"frequencyAndTotalEnergy\" registers";
        return false;
    }

    if (reply->isFinished()) {
        return false; // Broadcast reply returns immediatly
    }

    m_pendingUpdateReplies.append(reply);
    connect(reply, &ModbusRtuReply::finished, this, [this, reply](){
        handleModbusError(reply->error());
        m_pendingUpdateReplies.removeAll(reply);

        if (reply->error() != ModbusRtuReply::NoError) {
            verifyUpdateFinished();
            return;
        }

        QVector<quint16> blockValues = reply->result();
        qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "<-- Response from reading block \"frequencyAndTotalEnergy\" register" << 0 << "size:" << 0 << blockValues;
        verifyUpdateFinished();
    });

    connect(reply, &ModbusRtuReply::errorOccurred, this, [reply] (ModbusRtuReply::Error error){
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "ModbusRtu reply error occurred while updating block \"frequencyAndTotalEnergy\" registers" << error << reply->errorString();
    });

    return true;
}

void a-eberle-pqi-da-smartModbusRtuConnection::updateTotalCurrentPower()
{
    // Update registers from Total system power
    qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "--> Read \"Total system power\" register:" << 1964 << "size:" << 2;
    ModbusRtuReply *reply = readTotalCurrentPower();
    if (!reply) {
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Error occurred while reading \"Total system power\" registers";
        return;
    }

    if (!reply->isFinished()) {
        connect(reply, &ModbusRtuReply::finished, this, [this, reply](){
            handleModbusError(reply->error());
            if (reply->error() == ModbusRtuReply::NoError) {
                QVector<quint16> values = reply->result();
                qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "<-- Response from \"Total system power\" register" << 1964 << "size:" << 2 << values;
                processTotalCurrentPowerRegisterValues(values);
            }
        });

        connect(reply, &ModbusRtuReply::errorOccurred, this, [reply] (ModbusRtuReply::Error error){
            qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "ModbusRtu reply error occurred while updating \"Total system power\" registers" << error << reply->errorString();
        });
    }
}

void a-eberle-pqi-da-smartModbusRtuConnection::updatePowerPhaseA()
{
    // Update registers from Power phase L1
    qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "--> Read \"Power phase L1\" register:" << 1946 << "size:" << 2;
    ModbusRtuReply *reply = readPowerPhaseA();
    if (!reply) {
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Error occurred while reading \"Power phase L1\" registers";
        return;
    }

    if (!reply->isFinished()) {
        connect(reply, &ModbusRtuReply::finished, this, [this, reply](){
            handleModbusError(reply->error());
            if (reply->error() == ModbusRtuReply::NoError) {
                QVector<quint16> values = reply->result();
                qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "<-- Response from \"Power phase L1\" register" << 1946 << "size:" << 2 << values;
                processPowerPhaseARegisterValues(values);
            }
        });

        connect(reply, &ModbusRtuReply::errorOccurred, this, [reply] (ModbusRtuReply::Error error){
            qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "ModbusRtu reply error occurred while updating \"Power phase L1\" registers" << error << reply->errorString();
        });
    }
}

void a-eberle-pqi-da-smartModbusRtuConnection::updatePowerPhaseB()
{
    // Update registers from Power phase L2
    qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "--> Read \"Power phase L2\" register:" << 1952 << "size:" << 2;
    ModbusRtuReply *reply = readPowerPhaseB();
    if (!reply) {
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Error occurred while reading \"Power phase L2\" registers";
        return;
    }

    if (!reply->isFinished()) {
        connect(reply, &ModbusRtuReply::finished, this, [this, reply](){
            handleModbusError(reply->error());
            if (reply->error() == ModbusRtuReply::NoError) {
                QVector<quint16> values = reply->result();
                qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "<-- Response from \"Power phase L2\" register" << 1952 << "size:" << 2 << values;
                processPowerPhaseBRegisterValues(values);
            }
        });

        connect(reply, &ModbusRtuReply::errorOccurred, this, [reply] (ModbusRtuReply::Error error){
            qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "ModbusRtu reply error occurred while updating \"Power phase L2\" registers" << error << reply->errorString();
        });
    }
}

void a-eberle-pqi-da-smartModbusRtuConnection::updatePowerPhaseC()
{
    // Update registers from Power phase L3
    qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "--> Read \"Power phase L3\" register:" << 1958 << "size:" << 2;
    ModbusRtuReply *reply = readPowerPhaseC();
    if (!reply) {
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Error occurred while reading \"Power phase L3\" registers";
        return;
    }

    if (!reply->isFinished()) {
        connect(reply, &ModbusRtuReply::finished, this, [this, reply](){
            handleModbusError(reply->error());
            if (reply->error() == ModbusRtuReply::NoError) {
                QVector<quint16> values = reply->result();
                qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "<-- Response from \"Power phase L3\" register" << 1958 << "size:" << 2 << values;
                processPowerPhaseCRegisterValues(values);
            }
        });

        connect(reply, &ModbusRtuReply::errorOccurred, this, [reply] (ModbusRtuReply::Error error){
            qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "ModbusRtu reply error occurred while updating \"Power phase L3\" registers" << error << reply->errorString();
        });
    }
}

void a-eberle-pqi-da-smartModbusRtuConnection::updateTotalEnergyConsumed()
{
    // Update registers from Total energy consumed
    qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "--> Read \"Total energy consumed\" register:" << 2184 << "size:" << 2;
    ModbusRtuReply *reply = readTotalEnergyConsumed();
    if (!reply) {
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Error occurred while reading \"Total energy consumed\" registers";
        return;
    }

    if (!reply->isFinished()) {
        connect(reply, &ModbusRtuReply::finished, this, [this, reply](){
            handleModbusError(reply->error());
            if (reply->error() == ModbusRtuReply::NoError) {
                QVector<quint16> values = reply->result();
                qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "<-- Response from \"Total energy consumed\" register" << 2184 << "size:" << 2 << values;
                processTotalEnergyConsumedRegisterValues(values);
            }
        });

        connect(reply, &ModbusRtuReply::errorOccurred, this, [reply] (ModbusRtuReply::Error error){
            qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "ModbusRtu reply error occurred while updating \"Total energy consumed\" registers" << error << reply->errorString();
        });
    }
}

void a-eberle-pqi-da-smartModbusRtuConnection::updateTotalEnergyProduced()
{
    // Update registers from Total energy produced
    qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "--> Read \"Total energy produced\" register:" << 2176 << "size:" << 2;
    ModbusRtuReply *reply = readTotalEnergyProduced();
    if (!reply) {
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Error occurred while reading \"Total energy produced\" registers";
        return;
    }

    if (!reply->isFinished()) {
        connect(reply, &ModbusRtuReply::finished, this, [this, reply](){
            handleModbusError(reply->error());
            if (reply->error() == ModbusRtuReply::NoError) {
                QVector<quint16> values = reply->result();
                qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "<-- Response from \"Total energy produced\" register" << 2176 << "size:" << 2 << values;
                processTotalEnergyProducedRegisterValues(values);
            }
        });

        connect(reply, &ModbusRtuReply::errorOccurred, this, [reply] (ModbusRtuReply::Error error){
            qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "ModbusRtu reply error occurred while updating \"Total energy produced\" registers" << error << reply->errorString();
        });
    }
}

void a-eberle-pqi-da-smartModbusRtuConnection::updateFrequency()
{
    // Update registers from Frequency
    qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "--> Read \"Frequency\" register:" << 1008 << "size:" << 2;
    ModbusRtuReply *reply = readFrequency();
    if (!reply) {
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Error occurred while reading \"Frequency\" registers";
        return;
    }

    if (!reply->isFinished()) {
        connect(reply, &ModbusRtuReply::finished, this, [this, reply](){
            handleModbusError(reply->error());
            if (reply->error() == ModbusRtuReply::NoError) {
                QVector<quint16> values = reply->result();
                qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "<-- Response from \"Frequency\" register" << 1008 << "size:" << 2 << values;
                processFrequencyRegisterValues(values);
            }
        });

        connect(reply, &ModbusRtuReply::errorOccurred, this, [reply] (ModbusRtuReply::Error error){
            qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "ModbusRtu reply error occurred while updating \"Frequency\" registers" << error << reply->errorString();
        });
    }
}

void a-eberle-pqi-da-smartModbusRtuConnection::updateVoltagePhaseA()
{
    // Update registers from Voltage phase L1
    qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "--> Read \"Voltage phase L1\" register:" << 1010 << "size:" << 2;
    ModbusRtuReply *reply = readVoltagePhaseA();
    if (!reply) {
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Error occurred while reading \"Voltage phase L1\" registers";
        return;
    }

    if (!reply->isFinished()) {
        connect(reply, &ModbusRtuReply::finished, this, [this, reply](){
            handleModbusError(reply->error());
            if (reply->error() == ModbusRtuReply::NoError) {
                QVector<quint16> values = reply->result();
                qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "<-- Response from \"Voltage phase L1\" register" << 1010 << "size:" << 2 << values;
                processVoltagePhaseARegisterValues(values);
            }
        });

        connect(reply, &ModbusRtuReply::errorOccurred, this, [reply] (ModbusRtuReply::Error error){
            qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "ModbusRtu reply error occurred while updating \"Voltage phase L1\" registers" << error << reply->errorString();
        });
    }
}

void a-eberle-pqi-da-smartModbusRtuConnection::updateVoltagePhaseB()
{
    // Update registers from Voltage phase L2
    qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "--> Read \"Voltage phase L2\" register:" << 1012 << "size:" << 2;
    ModbusRtuReply *reply = readVoltagePhaseB();
    if (!reply) {
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Error occurred while reading \"Voltage phase L2\" registers";
        return;
    }

    if (!reply->isFinished()) {
        connect(reply, &ModbusRtuReply::finished, this, [this, reply](){
            handleModbusError(reply->error());
            if (reply->error() == ModbusRtuReply::NoError) {
                QVector<quint16> values = reply->result();
                qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "<-- Response from \"Voltage phase L2\" register" << 1012 << "size:" << 2 << values;
                processVoltagePhaseBRegisterValues(values);
            }
        });

        connect(reply, &ModbusRtuReply::errorOccurred, this, [reply] (ModbusRtuReply::Error error){
            qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "ModbusRtu reply error occurred while updating \"Voltage phase L2\" registers" << error << reply->errorString();
        });
    }
}

void a-eberle-pqi-da-smartModbusRtuConnection::updateVoltagePhaseC()
{
    // Update registers from Voltage phase L3
    qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "--> Read \"Voltage phase L3\" register:" << 1014 << "size:" << 2;
    ModbusRtuReply *reply = readVoltagePhaseC();
    if (!reply) {
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Error occurred while reading \"Voltage phase L3\" registers";
        return;
    }

    if (!reply->isFinished()) {
        connect(reply, &ModbusRtuReply::finished, this, [this, reply](){
            handleModbusError(reply->error());
            if (reply->error() == ModbusRtuReply::NoError) {
                QVector<quint16> values = reply->result();
                qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "<-- Response from \"Voltage phase L3\" register" << 1014 << "size:" << 2 << values;
                processVoltagePhaseCRegisterValues(values);
            }
        });

        connect(reply, &ModbusRtuReply::errorOccurred, this, [reply] (ModbusRtuReply::Error error){
            qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "ModbusRtu reply error occurred while updating \"Voltage phase L3\" registers" << error << reply->errorString();
        });
    }
}

void a-eberle-pqi-da-smartModbusRtuConnection::updateCurrentPhaseA()
{
    // Update registers from Current phase L1
    qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "--> Read \"Current phase L1\" register:" << 1586 << "size:" << 2;
    ModbusRtuReply *reply = readCurrentPhaseA();
    if (!reply) {
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Error occurred while reading \"Current phase L1\" registers";
        return;
    }

    if (!reply->isFinished()) {
        connect(reply, &ModbusRtuReply::finished, this, [this, reply](){
            handleModbusError(reply->error());
            if (reply->error() == ModbusRtuReply::NoError) {
                QVector<quint16> values = reply->result();
                qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "<-- Response from \"Current phase L1\" register" << 1586 << "size:" << 2 << values;
                processCurrentPhaseARegisterValues(values);
            }
        });

        connect(reply, &ModbusRtuReply::errorOccurred, this, [reply] (ModbusRtuReply::Error error){
            qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "ModbusRtu reply error occurred while updating \"Current phase L1\" registers" << error << reply->errorString();
        });
    }
}

void a-eberle-pqi-da-smartModbusRtuConnection::updateCurrentPhaseB()
{
    // Update registers from Current phase L2
    qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "--> Read \"Current phase L2\" register:" << 1588 << "size:" << 2;
    ModbusRtuReply *reply = readCurrentPhaseB();
    if (!reply) {
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Error occurred while reading \"Current phase L2\" registers";
        return;
    }

    if (!reply->isFinished()) {
        connect(reply, &ModbusRtuReply::finished, this, [this, reply](){
            handleModbusError(reply->error());
            if (reply->error() == ModbusRtuReply::NoError) {
                QVector<quint16> values = reply->result();
                qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "<-- Response from \"Current phase L2\" register" << 1588 << "size:" << 2 << values;
                processCurrentPhaseBRegisterValues(values);
            }
        });

        connect(reply, &ModbusRtuReply::errorOccurred, this, [reply] (ModbusRtuReply::Error error){
            qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "ModbusRtu reply error occurred while updating \"Current phase L2\" registers" << error << reply->errorString();
        });
    }
}

void a-eberle-pqi-da-smartModbusRtuConnection::updateCurrentPhaseC()
{
    // Update registers from Current phase L3
    qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "--> Read \"Current phase L3\" register:" << 1590 << "size:" << 2;
    ModbusRtuReply *reply = readCurrentPhaseC();
    if (!reply) {
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Error occurred while reading \"Current phase L3\" registers";
        return;
    }

    if (!reply->isFinished()) {
        connect(reply, &ModbusRtuReply::finished, this, [this, reply](){
            handleModbusError(reply->error());
            if (reply->error() == ModbusRtuReply::NoError) {
                QVector<quint16> values = reply->result();
                qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "<-- Response from \"Current phase L3\" register" << 1590 << "size:" << 2 << values;
                processCurrentPhaseCRegisterValues(values);
            }
        });

        connect(reply, &ModbusRtuReply::errorOccurred, this, [reply] (ModbusRtuReply::Error error){
            qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "ModbusRtu reply error occurred while updating \"Current phase L3\" registers" << error << reply->errorString();
        });
    }
}

void a-eberle-pqi-da-smartModbusRtuConnection::updatePhaseVoltageAndFrequencyBlock()
{
    // Update register block "phaseVoltageAndFrequency"
    qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "--> Read block \"phaseVoltageAndFrequency\" registers from:" << 1008 << "size:" << 8;
    ModbusRtuReply *reply = m_modbusRtuMaster->readHoldingRegister(m_slaveId, 1008, 8);
    if (!reply) {
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Error occurred while reading block \"phaseVoltageAndFrequency\" registers";
        return;
    }

    if (!reply->isFinished()) {
        connect(reply, &ModbusRtuReply::finished, this, [this, reply](){
            handleModbusError(reply->error());
            if (reply->error() == ModbusRtuReply::NoError) {
                QVector<quint16> blockValues = reply->result();
                qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "<-- Response from reading block \"phaseVoltageAndFrequency\" register" << 1008 << "size:" << 8 << blockValues;
                processFrequencyRegisterValues(blockValues.mid(0, 2));
                processVoltagePhaseARegisterValues(blockValues.mid(2, 2));
                processVoltagePhaseBRegisterValues(blockValues.mid(4, 2));
                processVoltagePhaseCRegisterValues(blockValues.mid(6, 2));
            }
        });

        connect(reply, &ModbusRtuReply::errorOccurred, this, [reply] (ModbusRtuReply::Error error){
            qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "ModbusRtu reply error occurred while updating block \"phaseVoltageAndFrequency\" registers" << error << reply->errorString();
        });
    }
}

void a-eberle-pqi-da-smartModbusRtuConnection::updatePhaseCurrentBlock()
{
    // Update register block "phaseCurrent"
    qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "--> Read block \"phaseCurrent\" registers from:" << 1586 << "size:" << 6;
    ModbusRtuReply *reply = m_modbusRtuMaster->readHoldingRegister(m_slaveId, 1586, 6);
    if (!reply) {
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Error occurred while reading block \"phaseCurrent\" registers";
        return;
    }

    if (!reply->isFinished()) {
        connect(reply, &ModbusRtuReply::finished, this, [this, reply](){
            handleModbusError(reply->error());
            if (reply->error() == ModbusRtuReply::NoError) {
                QVector<quint16> blockValues = reply->result();
                qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "<-- Response from reading block \"phaseCurrent\" register" << 1586 << "size:" << 6 << blockValues;
                processCurrentPhaseARegisterValues(blockValues.mid(0, 2));
                processCurrentPhaseBRegisterValues(blockValues.mid(2, 2));
                processCurrentPhaseCRegisterValues(blockValues.mid(4, 2));
            }
        });

        connect(reply, &ModbusRtuReply::errorOccurred, this, [reply] (ModbusRtuReply::Error error){
            qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "ModbusRtu reply error occurred while updating block \"phaseCurrent\" registers" << error << reply->errorString();
        });
    }
}

void a-eberle-pqi-da-smartModbusRtuConnection::updatePhasePowerBlock()
{
    // Update register block "phasePower"
    qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "--> Read block \"phasePower\" registers from:" << 0 << "size:" << 0;
    ModbusRtuReply *reply = m_modbusRtuMaster->readHoldingRegister(m_slaveId, 0, 0);
    if (!reply) {
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Error occurred while reading block \"phasePower\" registers";
        return;
    }

    if (!reply->isFinished()) {
        connect(reply, &ModbusRtuReply::finished, this, [this, reply](){
            handleModbusError(reply->error());
            if (reply->error() == ModbusRtuReply::NoError) {
                QVector<quint16> blockValues = reply->result();
                qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "<-- Response from reading block \"phasePower\" register" << 0 << "size:" << 0 << blockValues;
            }
        });

        connect(reply, &ModbusRtuReply::errorOccurred, this, [reply] (ModbusRtuReply::Error error){
            qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "ModbusRtu reply error occurred while updating block \"phasePower\" registers" << error << reply->errorString();
        });
    }
}

void a-eberle-pqi-da-smartModbusRtuConnection::updateFrequencyAndTotalEnergyBlock()
{
    // Update register block "frequencyAndTotalEnergy"
    qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "--> Read block \"frequencyAndTotalEnergy\" registers from:" << 0 << "size:" << 0;
    ModbusRtuReply *reply = m_modbusRtuMaster->readHoldingRegister(m_slaveId, 0, 0);
    if (!reply) {
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Error occurred while reading block \"frequencyAndTotalEnergy\" registers";
        return;
    }

    if (!reply->isFinished()) {
        connect(reply, &ModbusRtuReply::finished, this, [this, reply](){
            handleModbusError(reply->error());
            if (reply->error() == ModbusRtuReply::NoError) {
                QVector<quint16> blockValues = reply->result();
                qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "<-- Response from reading block \"frequencyAndTotalEnergy\" register" << 0 << "size:" << 0 << blockValues;
            }
        });

        connect(reply, &ModbusRtuReply::errorOccurred, this, [reply] (ModbusRtuReply::Error error){
            qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "ModbusRtu reply error occurred while updating block \"frequencyAndTotalEnergy\" registers" << error << reply->errorString();
        });
    }
}

ModbusRtuReply *a-eberle-pqi-da-smartModbusRtuConnection::readTotalCurrentPower()
{
    return m_modbusRtuMaster->readHoldingRegister(m_slaveId, 1964, 2);
}

ModbusRtuReply *a-eberle-pqi-da-smartModbusRtuConnection::readPowerPhaseA()
{
    return m_modbusRtuMaster->readHoldingRegister(m_slaveId, 1946, 2);
}

ModbusRtuReply *a-eberle-pqi-da-smartModbusRtuConnection::readPowerPhaseB()
{
    return m_modbusRtuMaster->readHoldingRegister(m_slaveId, 1952, 2);
}

ModbusRtuReply *a-eberle-pqi-da-smartModbusRtuConnection::readPowerPhaseC()
{
    return m_modbusRtuMaster->readHoldingRegister(m_slaveId, 1958, 2);
}

ModbusRtuReply *a-eberle-pqi-da-smartModbusRtuConnection::readTotalEnergyConsumed()
{
    return m_modbusRtuMaster->readHoldingRegister(m_slaveId, 2184, 2);
}

ModbusRtuReply *a-eberle-pqi-da-smartModbusRtuConnection::readTotalEnergyProduced()
{
    return m_modbusRtuMaster->readHoldingRegister(m_slaveId, 2176, 2);
}

ModbusRtuReply *a-eberle-pqi-da-smartModbusRtuConnection::readFrequency()
{
    return m_modbusRtuMaster->readHoldingRegister(m_slaveId, 1008, 2);
}

ModbusRtuReply *a-eberle-pqi-da-smartModbusRtuConnection::readVoltagePhaseA()
{
    return m_modbusRtuMaster->readHoldingRegister(m_slaveId, 1010, 2);
}

ModbusRtuReply *a-eberle-pqi-da-smartModbusRtuConnection::readVoltagePhaseB()
{
    return m_modbusRtuMaster->readHoldingRegister(m_slaveId, 1012, 2);
}

ModbusRtuReply *a-eberle-pqi-da-smartModbusRtuConnection::readVoltagePhaseC()
{
    return m_modbusRtuMaster->readHoldingRegister(m_slaveId, 1014, 2);
}

ModbusRtuReply *a-eberle-pqi-da-smartModbusRtuConnection::readCurrentPhaseA()
{
    return m_modbusRtuMaster->readHoldingRegister(m_slaveId, 1586, 2);
}

ModbusRtuReply *a-eberle-pqi-da-smartModbusRtuConnection::readCurrentPhaseB()
{
    return m_modbusRtuMaster->readHoldingRegister(m_slaveId, 1588, 2);
}

ModbusRtuReply *a-eberle-pqi-da-smartModbusRtuConnection::readCurrentPhaseC()
{
    return m_modbusRtuMaster->readHoldingRegister(m_slaveId, 1590, 2);
}

ModbusRtuReply *a-eberle-pqi-da-smartModbusRtuConnection::readBlockPhaseVoltageAndFrequency()
{
    return m_modbusRtuMaster->readHoldingRegister(m_slaveId, 1008, 8);
}

ModbusRtuReply *a-eberle-pqi-da-smartModbusRtuConnection::readBlockPhaseCurrent()
{
    return m_modbusRtuMaster->readHoldingRegister(m_slaveId, 1586, 6);
}

ModbusRtuReply *a-eberle-pqi-da-smartModbusRtuConnection::readBlockPhasePower()
{
    return m_modbusRtuMaster->readHoldingRegister(m_slaveId, 0, 0);
}

ModbusRtuReply *a-eberle-pqi-da-smartModbusRtuConnection::readBlockFrequencyAndTotalEnergy()
{
    return m_modbusRtuMaster->readHoldingRegister(m_slaveId, 0, 0);
}

void a-eberle-pqi-da-smartModbusRtuConnection::processTotalCurrentPowerRegisterValues(const QVector<quint16> values)
{
    float receivedTotalCurrentPower = ModbusDataUtils::convertToFloat32(values, m_endianness);
    emit totalCurrentPowerReadFinished(receivedTotalCurrentPower);

    if (m_totalCurrentPower != receivedTotalCurrentPower) {
        m_totalCurrentPower = receivedTotalCurrentPower;
        emit totalCurrentPowerChanged(m_totalCurrentPower);
    }
}

void a-eberle-pqi-da-smartModbusRtuConnection::processPowerPhaseARegisterValues(const QVector<quint16> values)
{
    float receivedPowerPhaseA = ModbusDataUtils::convertToFloat32(values, m_endianness);
    emit powerPhaseAReadFinished(receivedPowerPhaseA);

    if (m_powerPhaseA != receivedPowerPhaseA) {
        m_powerPhaseA = receivedPowerPhaseA;
        emit powerPhaseAChanged(m_powerPhaseA);
    }
}

void a-eberle-pqi-da-smartModbusRtuConnection::processPowerPhaseBRegisterValues(const QVector<quint16> values)
{
    float receivedPowerPhaseB = ModbusDataUtils::convertToFloat32(values, m_endianness);
    emit powerPhaseBReadFinished(receivedPowerPhaseB);

    if (m_powerPhaseB != receivedPowerPhaseB) {
        m_powerPhaseB = receivedPowerPhaseB;
        emit powerPhaseBChanged(m_powerPhaseB);
    }
}

void a-eberle-pqi-da-smartModbusRtuConnection::processPowerPhaseCRegisterValues(const QVector<quint16> values)
{
    float receivedPowerPhaseC = ModbusDataUtils::convertToFloat32(values, m_endianness);
    emit powerPhaseCReadFinished(receivedPowerPhaseC);

    if (m_powerPhaseC != receivedPowerPhaseC) {
        m_powerPhaseC = receivedPowerPhaseC;
        emit powerPhaseCChanged(m_powerPhaseC);
    }
}

void a-eberle-pqi-da-smartModbusRtuConnection::processTotalEnergyConsumedRegisterValues(const QVector<quint16> values)
{
    float receivedTotalEnergyConsumed = ModbusDataUtils::convertToFloat32(values, m_endianness);
    emit totalEnergyConsumedReadFinished(receivedTotalEnergyConsumed);

    if (m_totalEnergyConsumed != receivedTotalEnergyConsumed) {
        m_totalEnergyConsumed = receivedTotalEnergyConsumed;
        emit totalEnergyConsumedChanged(m_totalEnergyConsumed);
    }
}

void a-eberle-pqi-da-smartModbusRtuConnection::processTotalEnergyProducedRegisterValues(const QVector<quint16> values)
{
    float receivedTotalEnergyProduced = ModbusDataUtils::convertToFloat32(values, m_endianness);
    emit totalEnergyProducedReadFinished(receivedTotalEnergyProduced);

    if (m_totalEnergyProduced != receivedTotalEnergyProduced) {
        m_totalEnergyProduced = receivedTotalEnergyProduced;
        emit totalEnergyProducedChanged(m_totalEnergyProduced);
    }
}

void a-eberle-pqi-da-smartModbusRtuConnection::processFrequencyRegisterValues(const QVector<quint16> values)
{
    float receivedFrequency = ModbusDataUtils::convertToFloat32(values, m_endianness);
    emit frequencyReadFinished(receivedFrequency);

    if (m_frequency != receivedFrequency) {
        m_frequency = receivedFrequency;
        emit frequencyChanged(m_frequency);
    }
}

void a-eberle-pqi-da-smartModbusRtuConnection::processVoltagePhaseARegisterValues(const QVector<quint16> values)
{
    float receivedVoltagePhaseA = ModbusDataUtils::convertToFloat32(values, m_endianness);
    emit voltagePhaseAReadFinished(receivedVoltagePhaseA);

    if (m_voltagePhaseA != receivedVoltagePhaseA) {
        m_voltagePhaseA = receivedVoltagePhaseA;
        emit voltagePhaseAChanged(m_voltagePhaseA);
    }
}

void a-eberle-pqi-da-smartModbusRtuConnection::processVoltagePhaseBRegisterValues(const QVector<quint16> values)
{
    float receivedVoltagePhaseB = ModbusDataUtils::convertToFloat32(values, m_endianness);
    emit voltagePhaseBReadFinished(receivedVoltagePhaseB);

    if (m_voltagePhaseB != receivedVoltagePhaseB) {
        m_voltagePhaseB = receivedVoltagePhaseB;
        emit voltagePhaseBChanged(m_voltagePhaseB);
    }
}

void a-eberle-pqi-da-smartModbusRtuConnection::processVoltagePhaseCRegisterValues(const QVector<quint16> values)
{
    float receivedVoltagePhaseC = ModbusDataUtils::convertToFloat32(values, m_endianness);
    emit voltagePhaseCReadFinished(receivedVoltagePhaseC);

    if (m_voltagePhaseC != receivedVoltagePhaseC) {
        m_voltagePhaseC = receivedVoltagePhaseC;
        emit voltagePhaseCChanged(m_voltagePhaseC);
    }
}

void a-eberle-pqi-da-smartModbusRtuConnection::processCurrentPhaseARegisterValues(const QVector<quint16> values)
{
    float receivedCurrentPhaseA = ModbusDataUtils::convertToFloat32(values, m_endianness);
    emit currentPhaseAReadFinished(receivedCurrentPhaseA);

    if (m_currentPhaseA != receivedCurrentPhaseA) {
        m_currentPhaseA = receivedCurrentPhaseA;
        emit currentPhaseAChanged(m_currentPhaseA);
    }
}

void a-eberle-pqi-da-smartModbusRtuConnection::processCurrentPhaseBRegisterValues(const QVector<quint16> values)
{
    float receivedCurrentPhaseB = ModbusDataUtils::convertToFloat32(values, m_endianness);
    emit currentPhaseBReadFinished(receivedCurrentPhaseB);

    if (m_currentPhaseB != receivedCurrentPhaseB) {
        m_currentPhaseB = receivedCurrentPhaseB;
        emit currentPhaseBChanged(m_currentPhaseB);
    }
}

void a-eberle-pqi-da-smartModbusRtuConnection::processCurrentPhaseCRegisterValues(const QVector<quint16> values)
{
    float receivedCurrentPhaseC = ModbusDataUtils::convertToFloat32(values, m_endianness);
    emit currentPhaseCReadFinished(receivedCurrentPhaseC);

    if (m_currentPhaseC != receivedCurrentPhaseC) {
        m_currentPhaseC = receivedCurrentPhaseC;
        emit currentPhaseCChanged(m_currentPhaseC);
    }
}

void a-eberle-pqi-da-smartModbusRtuConnection::handleModbusError(ModbusRtuReply::Error error)
{
    if (error == ModbusRtuReply::NoError) {
        // Reset the communication counter and we know we can reach the device
        m_communicationFailedCounter = 0;
        if (!m_communicationWorking)
            qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Received a reply without any errors. The communication with the device seems to work now.";

        m_communicationWorking = true;
        evaluateReachableState();
    } else {
        m_communicationFailedCounter++;
        if (m_communicationWorking && m_communicationFailedCounter >= m_communicationFailedMax) {
            m_communicationWorking = false;
            qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Received" << m_communicationFailedCounter << "errors while communicating with the RTU master. Mark as not reachable until the communication works again.";
            evaluateReachableState();
        }
    }
}

void a-eberle-pqi-da-smartModbusRtuConnection::testReachability()
{
    if (m_checkRechableReply)
        return;

    // Try to read the check reachability register voltagePhaseA in order to verify if the communication is working or not.
    qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "--> Test reachability by reading \"Voltage phase L1\" register:" << 1010 << "size:" << 2;
    m_checkRechableReply = readVoltagePhaseA();
    if (!m_checkRechableReply) {
        qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Error occurred verifying reachability by reading \"Voltage phase L1\" register";
        onReachabilityCheckFailed();
        return;
    }

    if (m_checkRechableReply->isFinished()) {
        m_checkRechableReply = nullptr;
        onReachabilityCheckFailed();
        return;
    }

    connect(m_checkRechableReply, &ModbusRtuReply::finished, this, [this](){
        // Note: we don't care about the result here, only the error
        handleModbusError(m_checkRechableReply->error());
        if (m_checkRechableReply->error() != ModbusRtuReply::NoError)
            onReachabilityCheckFailed();

        m_checkRechableReply = nullptr;
    });

    connect(m_checkRechableReply, &ModbusRtuReply::errorOccurred, this, [this] (ModbusRtuReply::Error error){
        qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "ModbusRtu reply error occurred while verifying reachability by reading \"Voltage phase L1\" register" << error << m_checkRechableReply->errorString();
    });
}

void a-eberle-pqi-da-smartModbusRtuConnection::verifyInitFinished()
{
    if (m_pendingInitReplies.isEmpty()) {
        finishInitialization(true);
    }
}

void a-eberle-pqi-da-smartModbusRtuConnection::finishInitialization(bool success)
{
    if (success) {
        qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Initialization finished of a-eberle-pqi-da-smartModbusRtuConnection finished successfully";
    } else {
        qCWarning(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Initialization finished of a-eberle-pqi-da-smartModbusRtuConnection failed.";
    }

    // Cleanup init
    delete m_initObject;
    m_initObject = nullptr;
    m_pendingInitReplies.clear();

    emit initializationFinished(success);
}

void a-eberle-pqi-da-smartModbusRtuConnection::verifyUpdateFinished()
{
    if (m_pendingUpdateReplies.isEmpty()) {
        emit updateFinished();
    }
}

void a-eberle-pqi-da-smartModbusRtuConnection::onReachabilityCheckFailed()
{
    m_checkReachableRetriesCount++;

    if (m_checkReachableRetriesCount <= m_checkReachableRetries) {
        qCDebug(dca-eberle-pqi-da-smartModbusRtuConnection()) << "Reachability test failed. Retry in on second" << m_checkReachableRetriesCount << "/" << m_checkReachableRetries;
        QTimer::singleShot(1000, this, &a-eberle-pqi-da-smartModbusRtuConnection::testReachability);
        return;
    }

    // The test reachability method failed, not retrying any more
    emit checkReachabilityFailed();
}

void a-eberle-pqi-da-smartModbusRtuConnection::evaluateReachableState()
{
    bool reachable = m_communicationWorking && m_modbusRtuMaster->connected();
    if (m_reachable == reachable)
        return;

    m_reachable = reachable;
    emit reachableChanged(m_reachable);
    m_checkReachableRetriesCount = 0;
}

QDebug operator<<(QDebug debug, a-eberle-pqi-da-smartModbusRtuConnection *a-eberle-pqi-da-smartModbusRtuConnection)
{
    debug.nospace().noquote() << "a-eberle-pqi-da-smartModbusRtuConnection(" << a-eberle-pqi-da-smartModbusRtuConnection->modbusRtuMaster()->modbusUuid().toString() << ", " << a-eberle-pqi-da-smartModbusRtuConnection->modbusRtuMaster()->serialPort() << ", slave ID:" << a-eberle-pqi-da-smartModbusRtuConnection->slaveId() << ")" << "\n";
    debug.nospace().noquote() << "    - Total system power: " << a-eberle-pqi-da-smartModbusRtuConnection->totalCurrentPower() << " [W]" << "\n";
    debug.nospace().noquote() << "    - Power phase L1: " << a-eberle-pqi-da-smartModbusRtuConnection->powerPhaseA() << " [W]" << "\n";
    debug.nospace().noquote() << "    - Power phase L2: " << a-eberle-pqi-da-smartModbusRtuConnection->powerPhaseB() << " [W]" << "\n";
    debug.nospace().noquote() << "    - Power phase L3: " << a-eberle-pqi-da-smartModbusRtuConnection->powerPhaseC() << " [W]" << "\n";
    debug.nospace().noquote() << "    - Total energy consumed: " << a-eberle-pqi-da-smartModbusRtuConnection->totalEnergyConsumed() << " [kWh]" << "\n";
    debug.nospace().noquote() << "    - Total energy produced: " << a-eberle-pqi-da-smartModbusRtuConnection->totalEnergyProduced() << " [kWh]" << "\n";
    debug.nospace().noquote() << "    - Frequency: " << a-eberle-pqi-da-smartModbusRtuConnection->frequency() << " [Hz]" << "\n";
    debug.nospace().noquote() << "    - Voltage phase L1: " << a-eberle-pqi-da-smartModbusRtuConnection->voltagePhaseA() << " [V]" << "\n";
    debug.nospace().noquote() << "    - Voltage phase L2: " << a-eberle-pqi-da-smartModbusRtuConnection->voltagePhaseB() << " [V]" << "\n";
    debug.nospace().noquote() << "    - Voltage phase L3: " << a-eberle-pqi-da-smartModbusRtuConnection->voltagePhaseC() << " [V]" << "\n";
    debug.nospace().noquote() << "    - Current phase L1: " << a-eberle-pqi-da-smartModbusRtuConnection->currentPhaseA() << " [A]" << "\n";
    debug.nospace().noquote() << "    - Current phase L2: " << a-eberle-pqi-da-smartModbusRtuConnection->currentPhaseB() << " [A]" << "\n";
    debug.nospace().noquote() << "    - Current phase L3: " << a-eberle-pqi-da-smartModbusRtuConnection->currentPhaseC() << " [A]" << "\n";
    return debug.quote().space();
}

