# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
# This file has been autogenerated.
# Any changes in this file may be overwritten from qmake.
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

HEADERS += \
    $${PWD}/lambdamodbustcpconnection.h \

SOURCES += \
    $${PWD}/lambdamodbustcpconnection.cpp \
